[package]
name = "readline_number"
version = "0.1.0"
authors = ["hinata"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
numeric = { path = "./../numeric" }